version: "3"
services:
  angular:
    image: angular/ngcontainer:latest
    volumes:
      - ${PWD}:/home/circleci/project
    working_dir: /home/circleci/project
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
      - "8080:8080"