ANGULAR_PACKAGE_VERSION = ">=6.0.0-beta.0 <7.0.0"

PACKAGE_VERSION = "0.11.0-beta.2"

VERSION_PLACEHOLDER_REPLACEMENTS = {
    "0.0.0-NG": ANGULAR_PACKAGE_VERSION,
    "0.0.0-PLACEHOLDER": PACKAGE_VERSION,
}
