# Javascript Node CircleCI 2.0 configuration file
version: 2
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_key yarn-cache-{{ checksum "yarn.lock" }}
var_2: &node_image
  docker:
      - image: circleci/node:latest-browsers

jobs:
  build:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn install --silent
      - run: yarn gulp ci:build

      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ~/.cache/yarn

  lint:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn gulp ci:lint

  test:
    <<: *node_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn gulp ci:test

  deploy:
    <<: *node_image
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: *cache_key

      - run: yarn gulp deploy

      - store_artifacts:
          path: dist/releases

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
            - lint
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master