import './tasks/clean';
import './tasks/aot';
import './tasks/coverage';
import './tasks/default';
import './tasks/lint';
import './tasks/unit-test';
import './tasks/ci';
import './tasks/publish';
import './tasks/deploy-github';
